Anisotropic elasticity
VIXER13/nonlocal pull request #28
Opened 2024-09-22 16:44 UTC by UncleRais

Добавил анизотропный тензор упругости в механику.

2024-09-22 17:10 UTC, VIXER13 requested changes

2024-09-22 17:10 UTC, VIXER13 commented on libraries/solvers/solver_2d/mechanical/stiffness_matrix_2d.hpp
> +                                                               theories_types(parameters);
Откуда-то появились пробелы в конце строчки

2024-09-22 17:10 UTC, VIXER13 commented on libraries/config/mechanical_material_data.hpp
> +        if (config.is_number()) {
Перенести с 40-й строчки в if
```suggestion
        if (const auto& conf = config[name]; config.is_number()) {
```

2024-09-22 17:10 UTC, VIXER13 commented on libraries/config/mechanical_material_data.hpp
> +            parameter[0] = conf.get<T>();
Можно объединить две строчки в одну
```suggestion
            parameter.fill(conf.get<T>());
```

2024-09-23 17:07 UTC, UncleRais commented on libraries/solvers/solver_2d/mechanical/stiffness_matrix_2d.hpp
> +    static constexpr std::size_t DoF = 2;
Убрал

2024-09-23 17:07 UTC, UncleRais commented on libraries/solvers/solver_2d/mechanical/stiffness_matrix_2d.hpp
> +                                                               theories_types(parameters);
Убрал

2024-09-23 17:08 UTC, UncleRais commented on libraries/config/mechanical_material_data.hpp
> +        if (config.is_number()) {
Перенес

2024-09-23 17:08 UTC, UncleRais commented on libraries/config/mechanical_material_data.hpp
> +            parameter[0] = conf.get<T>();
Объединил

2024-09-25 08:21 UTC, VIXER13 requested changes

2024-09-25 08:21 UTC, VIXER13 commented on libraries/config/mechanical_material_data.hpp
> +            throw std::domain_error{"The " + name + " should be either a number in the isotropic case, "
Если гипотеза, что Ey * nuxy == Ex * nuyx верна всегда, то стоит реализовать более сложную логику парсинга, так как для определения параметров материала нам достаточно всего трёх констант, вместо четырёх. То есть предлагаю обработать следующие ситуации:

- Изотропный случай (просто чекаем, что у нас лежат числа в соответствующих полях)
```
"youngs_modulus" : E
"poissons_ratio": nu
```

- Различные варианты ортотропного случая. Важно, что если мы работаем с ортотропным материалом, то "shear_modulus" становится обязательным параметром (он же не выразим через модулю Юнга и коэффициенты Пуассона?). Здесь думаю стоит обработать два основных варианта:

1. Когда один из коэффициентов лежит в json в виде массива, а второй в виде числа
```
"youngs_modulus" : [Ex, Ey]
"poissons_ratio": nu
"shear_modulus": G
```
```
"youngs_modulus" : E
"poissons_ratio": [nuxy, nuyx]
"shear_modulus": G
```

2. И второй большой случай, когда у нас оба коэффициента представлены в виде массивов, но в одном из массиве один из параметров не указан (то есть там лежит null)
```
"youngs_modulus" : [null, Ey]
"poissons_ratio": [nuxy, nuyx]
"shear_modulus": G
```
```
"youngs_modulus" : [Ex, null]
"poissons_ratio": [nuxy, nuyx]
"shear_modulus": G
```
```
"youngs_modulus" : [Ex, Ey]
"poissons_ratio": [null, nuyx]
"shear_modulus": G
```
```
"youngs_modulus" : [Ex, Ey]
"poissons_ratio": [nuxy, null]
"shear_modulus": G
```

- Ситуации, когда стоит кидать исключения:

1. Когда у нас заданы 4 константы
```
"youngs_modulus" : [Ex, Ey]
"poissons_ratio": [nuxy, nuyx]
"shear_modulus": G
```
2. Когда у нас больше одного null
```
"youngs_modulus" : [null, Ey]
"poissons_ratio": [nuxy, null]
"shear_modulus": G
```

Разумеется, такую сложную и разветвлённую логику стоит покрыть юнит тестами

2024-10-13 17:49 UTC, UncleRais commented on libraries/config/mechanical_material_data.hpp
> +            throw std::domain_error{"The " + name + " should be either a number in the isotropic case, "
Добавил это ветвление. По сути у нас есть варианты, когда задание матрицы идет относительно Ex (я назвал этот случай X_dominant) или относительно Ey (Y_dominant). Во время считывания и обработки параметров и null мы можем определить, какой у нас тип задания матрицы, его проинициализировать и передать дальше. Во время расчета самой матрицы изменений благодаря этому немного, что в целом логично, расчет матрицы не должно заботить, как мы получаем параметры.

2024-10-13 19:40 UTC, VIXER13 requested changes

2024-10-13 19:40 UTC, VIXER13 commented on libraries/config/mechanical_material_data.hpp
> +    void read_elasticity_parameters(std::array<T, 2>& parameter, const nlohmann::json& config, std::string name, std::array<size_t, 2>& null) {
```suggestion
    std::array<T, 2> read_elasticity_parameters(const nlohmann::json& config, std::string name) {
```

1. Здесь ситуация не требующая супер производительности, поэтому заполненный параметр можно просто вернуть (скорее всего компилятор это оптимизирует при помощи RVO)
2.  Для проверки null я бы написал отдельную функцию, которая будет чекать перед тем как парсить что-либо
3. Просто из своего опыта могу посоветовать структурировать сигнатуру функций по следующему порядку:
- output параметры, которые передаются по ссылке
- input/output параметры, которые передаются по ссылке (параметры, которые могут влиять на алгоритм, но в то же время меняются после его работы)
- input параметры, передающиеся по константной ссылке
- input параметры, передающиеся по значению
- input параметры, у которых есть дефолтные значения

Я это добавлю в заметку по styleguide

2024-10-13 19:40 UTC, VIXER13 commented on libraries/config/mechanical_material_data.hpp
> +        if (null >= 2) throw std::domain_error{"Not enough input parameters : too many null's"};
Предлагаю сделал логику проверок более явной и вынести её в отдельную функцию перед тем как парсить, тогда у нас будет один if, по типу такого:
```
if (check_elastic_parameters(config))
    throw std::domain_error{"одна ошибка и ты ошибся"};
```

2024-10-13 19:40 UTC, VIXER13 commented on libraries/solvers/solver_2d/mechanical/mechanical_parameters_2d_2.hpp
> +#ifndef NONLOCAL_MECHANICAL_PARAMETERS_2D_HPP
В новых модулях пиши просто `#pragma once`

2024-10-13 19:40 UTC, VIXER13 commented on libraries/solvers/solver_2d/mechanical/mechanical_parameters_2d_2.hpp
Я, конечно, не просил, но раз добавил возможность нелинейные параметры задавать, то думаю можно этим кодом заменить код из `mechanical_parameters_2d.hpp`, а дублёр удалить. Главное убедись, что всё корректно работает, как в изотропном, так и в ортотропном случаях

2024-10-13 19:40 UTC, VIXER13 commented on libraries/solvers/solver_2d/mechanical/mechanical_parameters_2d_2.hpp
> +using hooke_matrix = std::array<T, 6>;
Вроде бы остановились на 4 параметрах, почему 6?

2024-10-13 19:40 UTC, VIXER13 commented on libraries/solvers/solver_2d/mechanical/mechanical_parameters_2d_2.hpp
> +    return {     E / (T{1} - nu*nu),
Тут только изотропный случай, а ортотропный?

2024-10-13 19:40 UTC, VIXER13 commented on libraries/solvers/solver_2d/mechanical/mechanical_parameters_2d_2.hpp
Я бы на самом деле посоветовал сделать обобщение на нелинейные параметры потом, в будущих ПР. Всё равно код со стороны ассемблирования матрицы не готов к такому

2024-10-13 21:27 UTC, VIXER13 requested changes

2024-10-13 21:27 UTC, VIXER13 commented on libraries/config/mechanical_material_data.hpp
> +        if (poissons_ratio[1] <= 0 || poissons_ratio[1] >= 0.5)
По идее коэффициент Пуассона может быть отрицательным и его интервал может быть задан в пределах [-1, 0.5]

2024-10-13 21:27 UTC, VIXER13 commented on libraries/config/mechanical_material_data.hpp
> +    bool elasticity_parameters_correctness() {
```suggestion
    bool check_elasticity_parameters() const noexcept {
```
Поправил нейминг

2024-10-13 21:27 UTC, VIXER13 commented on libraries/config/mechanical_material_data.hpp
> +            return true;
```suggestion
            return false;
```
Потому что false, как правило, это плохо, а true -- хорошо, соответственно в проверке этой функции надо будет сделать замену на `if(!check_elasticity_parameters())`

2024-10-13 21:27 UTC, VIXER13 commented on libraries/config/mechanical_material_data.hpp
> +    }
Между функциями добавляй одну пустую строку

2024-10-13 21:27 UTC, VIXER13 commented on libraries/config/mechanical_material_data.hpp
> +    }
Перед областью видимости добавляй одну пустую строку

2024-10-13 21:27 UTC, VIXER13 commented on libraries/config/mechanical_material_data.hpp
> +        read_elasticity_parameters(youngs_modulus, config, "youngs_modulus", null_E);
Так будет выглядеть лучше
```suggestion
        youngs_modulus = read_elasticity_parameters(null_E, config, "youngs_modulus");
```

2024-10-13 21:27 UTC, VIXER13 commented on libraries/config/mechanical_material_data.hpp
> +        std::array<size_t, 2> null_E {0, 0}, null_nu {0, 0};
```suggestion
        std::array<bool, 2> null_E = {false, false};
        std::array<bool, 2> null_nu = {false, false};
```
size_t здесь выглядит избыточно, для флажков обычно используют bool. В целом, здесь можно заморочиться и вместо std::array использовать std::bitset, там же есть удобные методы по типу .all(), .any() и т.д.

2024-10-13 21:27 UTC, VIXER13 commented on libraries/config/mechanical_material_data.hpp
> +        read_elasticity_parameters(youngs_modulus, config, "youngs_modulus", null_E);
Но я бы при этом предложил всё-таки добавить функцию, которая будет вначале вычислять `null_E` и `null_nu`, а уже потом что-то парсить и делать с параметрами

2024-10-14 18:18 UTC, UncleRais commented on libraries/config/mechanical_material_data.hpp
> +        if (poissons_ratio[1] <= 0 || poissons_ratio[1] >= 0.5)
по идее может быть, но мы пока таких не считали задач. Добавлю, чтобы можно было

2024-10-14 18:21 UTC, UncleRais commented on libraries/config/mechanical_material_data.hpp
> +    bool elasticity_parameters_correctness() {
там тогда две одинаковые функции будет

2024-10-14 19:24 UTC, UncleRais commented on libraries/config/mechanical_material_data.hpp
> +        read_elasticity_parameters(youngs_modulus, config, "youngs_modulus", null_E);
сделал сначала обработку null, потом парсинг значений

2024-10-14 21:20 UTC, VIXER13 requested changes

2024-10-14 21:20 UTC, VIXER13 commented on libraries/config/mechanical_material_data.hpp
> +        auto fill_null = [&](std::string name) {
Здесь лямбда смотрится слишком громоздко. Обычно писать лямбды имеет смысл, когда они передаются в виде callback в какую-то другую функцию. Здесь будет лучше реализовать статическую функцию, в которую мы сразу передаём нужную ноду конфига, то есть примерно вот так
```
static std::bitset<2> check_is_null(const nlohmann::json& elastic_parameter) {
    std::bitset<2> is_null = "00";
    if (!elastic_parameter.is_number()) {
        if (elastic_parameter.is_array() && elastic_parameter.size() == 2) {
            is_null[0] = elastic_parameter[0].is_null();
            is_null[1] = elastic_parameter[1].is_null();
        } else
           throw std::domain_error{"The orthotropic material parameter must be specified as an array of dimension 2"};
    }
    return is_null;
}
```

А потом в коде, при инициализации писать сразу вот так
```
const std::bitset<2> is_null_E = check_is_null(config["youngs_modulus"]);
const std::bitset<2> is_null_nu = check_is_null(config["poissons_ratio"]);
```

2024-10-14 21:20 UTC, VIXER13 commented on libraries/config/mechanical_material_data.hpp
> +            throw std::domain_error{"Input format error. All elasticity parameters must be nonzero. Moreover : poissons_ratio in [-1, 0) U (0, 0.5]"};
В сообщении ошибки точка 0.5 выколотая, там в уравнениях деление на 0 получится если nu = 0.5 поставим.
Насчёт точки -1 не знаю, включена она или нет, надо будет изучить вопрос...

2024-10-14 21:20 UTC, VIXER13 commented on libraries/config/mechanical_material_data.hpp
> +        auto read_params = [&](std::string name, const std::bitset<2>& null) {
Здесь аналогично, переделать лямбду в статическую функцию с передачей нужной ноды конфига

2024-10-14 21:55 UTC, merged